Added user roles to the single and all user(s) getters
MetaCell/cloud-harness pull request #167
Opened 2021-01-27 22:07 UTC by ddelpiano

2021-01-28 09:11 UTC, zsinnema commented
please also add these functions to make the implementation of the realm roles complete:
```
get_user_realm_roles
get_current_user_realm_roles
user_has_realm_role
current_user_has_realm_role
```

2021-01-28 09:12 UTC, zsinnema requested changes
see my comments

2021-01-29 08:11 UTC, zsinnema requested changes

2021-01-29 08:11 UTC, zsinnema commented on libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> +        Tests if the user has the given role within the given client
"within the current realm"

2021-01-29 08:11 UTC, zsinnema commented on libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> +        Tests if the current user has the given role within the given client
"within the current realm"

2021-01-29 18:46 UTC, ddelpiano commented
@zsinnema I am merging this to fix the ifn deployment since currently we don't get clinician due to the logic to check the clinician or reviewer roles.
I fixed the latest changes requested already but if there is anything that you like me to change let me know and I will open a separate PR. Thx

2021-01-29 18:46 UTC, merged