Feature/192 update server applications
MetaCell/cloud-harness pull request #195
Opened 2021-02-10 18:17 UTC by lrebscher

**Manual testing:**
* Run harness-deployment and check if images build with success
* Install helm chart in minikube and check if applications start and show no error in logs

Closes #194

2021-02-11 13:29 UTC, filippomc approved these changes
Looks good and safe to merge

2021-02-16 10:22 UTC, zsinnema requested changes

2021-02-16 10:22 UTC, zsinnema commented on applications/common/server/Dockerfile
>  RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
musl-dev, python3-dev, gcc can be removed, they are part of the cloudharness-base image

2021-02-16 10:22 UTC, zsinnema commented on applications/common/server/Dockerfile
>  #RUN apk add psycopg2 libpq-dev python-dev
can be removed

2021-02-16 10:22 UTC, zsinnema commented on applications/common/server/common/__main__.py
> +connexion_app = connexion.App(__name__, specification_dir='./openapi/')
please wrap the whole initialisation into a CH function, looks to me that this is everytime the same

please use cloudharness.log and remove the unicorn logger stuff (2 weeks ago I formatted the default CH logger)

2021-02-16 10:22 UTC, zsinnema commented on applications/common/server/common/__main__.py
> +    connexion_app.run(port=8080)
may be better to remove the hardcoded 8080 port (set it via the FLASK_RUN_PORT or the command line parameter)

2021-02-16 10:22 UTC, zsinnema commented on applications/common/server/common/__main__.py
> +                          arguments={'title': 'CH service API'},
the title would then be configurable (a parameter of the init routine)

2021-02-16 10:22 UTC, zsinnema commented on applications/volumemanager/server/volumemanager/__init__.py
> +def init_app(app: Flask):
why add the routers if there are no files to server

2021-02-16 10:22 UTC, zsinnema commented on applications/volumemanager/server/volumemanager/__main__.py
> +import logging
use the ch logging

2021-02-16 10:22 UTC, zsinnema commented on applications/volumemanager/server/volumemanager/__main__.py
> +connexion_app = connexion.App(__name__, specification_dir="./openapi/", debug=True)
same here, may be we can create a default initializer

2021-02-16 10:22 UTC, zsinnema commented on applications/volumemanager/server/volumemanager/__main__.py
> +    connexion_app.debug = True
debug?

2021-02-16 10:22 UTC, zsinnema commented on applications/volumemanager/server/volumemanager/__main__.py
> +    connexion_app.run(port=5000)
remove port

2021-02-16 10:22 UTC, zsinnema commented on applications/workflows/server/workflows_api/__init__.py
> +def init_app(app: Flask):
why routers if there are no files?

2021-02-16 10:22 UTC, zsinnema commented on applications/workflows/server/workflows_api/__main__.py
> +import logging
ch logging

2021-02-16 10:22 UTC, zsinnema commented on applications/workflows/server/workflows_api/__main__.py
> +connexion_app = connexion.App(__name__, specification_dir="./openapi/", debug=True)
init function?

2021-02-16 10:22 UTC, zsinnema commented on applications/workflows/server/workflows_api/__main__.py
> +    connexion_app.debug = True
debug?

2021-02-16 10:22 UTC, zsinnema commented on applications/workflows/server/workflows_api/__main__.py
> +    connexion_app.run(port=5000)
remove port

2021-02-16 10:41 UTC, filippomc commented
@lrebscher most of the requests are coming from the default application templates. I can do the improvements starting from there so to keep this future proof

2021-02-16 10:57 UTC, zsinnema commented
> @lrebscher most of the requests are coming from the default application templates. I can do the improvements starting from there so to keep this future proof

sounds great!

2021-02-22 16:13 UTC, filippomc commented
Closing as merged with #199 in #229

2021-02-22 16:13 UTC, closed without merging