Feature/342: Update deprecated Kubernetes chart templates
MetaCell/cloud-harness pull request #345
Opened 2021-10-14 11:00 UTC by filippomc

* Update Argo subchart
* Update Jupyterhub templates
* Update Ingress template

Notice that with this deployment we also updated the applications versions, so regressions may come on applications that use them.
The most changes are coming on the Jupyterhub side: the configuration structure and files has been changed, so applications that are overriding may need to be updated accordingly.

Some known changes:

- apps/jupyterhub/deploy/values.yaml: auth.authenticator -> hub.config.JupyterHub.authenticator_class
- apps/jupyterhub/deploy/resources/jupyterhub_config.py has totally changed

Closes #342

2021-11-01 13:00 UTC, zsinnema requested changes

2021-11-01 13:00 UTC, zsinnema commented on applications/jupyterhub/deploy/values.yaml
> +    type: NodePort
nice!

2021-11-30 08:53 UTC, filippomc commented on applications/jupyterhub/deploy/values.yaml
> +  cmd: jupyterhub-singleuser
the change has been made because that script is not working anymore in that form (maybe path change, I don't remember exactly).

2021-11-30 10:51 UTC, zsinnema commented on applications/jupyterhub/deploy/values.yaml
> +  cmd: jupyterhub-singleuser
@filippomc let's try to figure this out. We should use some kind of bootstrap code here to enable hooks in the startup sequence. Like it is right now. For Minian the hook prepares the user workspace storage for Minian

2021-12-14 14:33 UTC, filippomc commented
converted to draft to fix an issue with multiple applications in the same cluster like 
```
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: ClusterRole "argo-view" in namespace "" exists and cannot be
 imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "osb2": current value is "osb2dev"; an
notation validation error: key "meta.helm.sh/release-namespace" must equal "osb2": current value is "osb2dev"
```

2022-01-11 09:57 UTC, filippomc commented on applications/jupyterhub/deploy/values.yaml
> +  cmd: jupyterhub-singleuser
@zsinnema done, can you please review again?

2022-01-18 14:40 UTC, zsinnema approved these changes

2022-01-18 15:07 UTC, merged