#401 chore: implement ch middleware for Flask and Django to set/get the ch application state. Refactored ch kc authentication to disconnect it from Flask
MetaCell/cloud-harness pull request #417
Opened 2022-02-02 12:47 UTC by zsinnema

Remove Flask dependency from CH Keycloak AuthClient

Closes #401 

Implemented solution:  implement ch middleware for Flask and Django to set/get the ch application state. Refactored ch kc authentication to disconnect it from Flask

How to test: ...

### Sanity checks:
- [x] The pull request is explicitly linked to the relevant issue(s)
- [x] The issue is well described: clearly states the problem and the general proposed solution(s)
- [ ] From the issue and the current pr it is explicitly stated how to test the current change
- [x] The labels in the issue set the scope and the type of issue (bug, feature, etc.)
- [x] All the automatic test checks are passing
- [ ] All the linked issues are included in one milestone
- [ ] All the linked issues are in the Review/QA column of the [board](https://app.zenhub.com/workspaces/cloud-harness-5fdb203b7e195b0015a273d7/board)
- [x ] All the linked issues are assigned

### Breaking changes (select one):
- [x] The present changes do not change the preexisting api in any way
- [ ] This pr and the issue are tagged as a `breaking-change`

### Possible deployment updates issues (select one):
- [x] There is no reason why deployments based on CloudHarness may break after the current update
- [ ] This pr and the issue are tagged as `alert:deployment`

### Test coverage (select one):
- [ ] Tests for the relevant cases are included in this pr
- [x] The changes included in this pr are out of the current test coverage scope

### Documentation (select one):
- [ ] The documentation has been updated to match the current changes
- [x] The changes included in this pr are out of the current documentation scope

2022-02-02 14:04 UTC, filippomc commented on libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> +                from flask import request, current_app
deprecation warning

2022-02-02 14:06 UTC, filippomc requested changes

2022-02-02 14:06 UTC, filippomc commented on libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> +            env = ch_state.get("env")
remove env

2022-02-02 14:06 UTC, filippomc commented on libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> +                env = 'development'
remove env

2022-02-02 14:06 UTC, filippomc commented on libraries/cloudharness-common/README.md
> +```
more docs and comments about the functionality of the middlewares

2022-02-02 14:06 UTC, filippomc commented on libraries/cloudharness-common/cloudharness/middleware/__init__.py
> +_state = ContextVar("ch_state", default={})
change to ch_authentication_token

2022-02-02 14:22 UTC, zsinnema commented on libraries/cloudharness-common/cloudharness/auth/keycloak/__init__.py
> +                from flask import request, current_app
done

2022-02-02 18:02 UTC, filippomc requested changes
Looks good, can you please just add/adapt some documentation bit here? https://github.com/MetaCell/cloud-harness/blob/develop/docs/applications/development/backend-development.md. Just a few words to tell the reader that this exist and a link to the middleware readme are fine

2022-02-03 14:34 UTC, filippomc approved these changes

2022-02-03 14:34 UTC, merged